### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by thanaus** [eavanvalkenburg/pysiaalarm#42]
Hello,

I use your library for a community project but I have an issue with a hkivision AX PRO alarm.

Everything works perfectly fine for all incoming lines except for the following line :
```
DEBUG:pysiaalarm.sia_server:Incoming line: CA2F0038"NULL"0000L0#7890[#0000|0000 00 000]_22:13:29,12-29-2022
DEBUG:pysiaalarm.base_sia_server:Parsed event: Content: #0000|0000 00 000]_22:13:29,12-29-2022, Zone: 0, Code: RP, Message:  00 000, Concerns: Unused, Type: Automatic Test, Description: Automatic communication test report, Account: 7890, Receiver: None, Prefix: L0, Timestamp: 2022-12-29 22:13:29, Length: 0038, Sequence: 0000, CRC: CA2F, Calc CRC: CA2F, Message type: Automatic Test, Encrypted Content: None, Full Message: "NULL"0000L0#7890[#0000|0000 00 000]_22:13:29,12-29-2022..
----------------------------------------
Exception happened during processing of request from ('185.238.6.49', 52770)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/dist-packages/pysiaalarm/sia_server.py", line 49, in handle
    raw = self.request.recv(1024)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------

```
I use the default test program run.py.
Any idea ?
Thanks a lot ;-)

**Comment by eavanvalkenburg** [comment]
Thanks for trying it out and reporting, my own alarm doesn't use this so I had to implement based on specs, I'll add this to the tests and see what's going wrong!
